sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t phoax/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true phoax/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "Docker-react2"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-955921749276"
  bucket_path: "Docker-react"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
